// Austin Baker
// C00265393
// CMPS 359 Android Programming
// Programming Assignment : #3
// Due Date : 10/20/20
// Program Description: Gives random math problems, converts dollars to pounds, displays a set map location on google maps, directs to a website via a button
// Certificate of Authenticity:
// I certify that the code of this project other than any code provided in the instructions or
// generated by the IDE for this assignment, is entirely my own work.


package com.example.app3_c00265393

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.navigation.Navigation
import com.example.app3_c00265393.ui.main.MainFragment
import kotlinx.android.synthetic.main.fragment_website.*

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_activity)
    }

}